### ISSUE TITLE
DB 설계

### ISSUE THREAD

**Issue by JustKode** [Dcom-KHU/D.Com-Homepage#3]
DB 설계를 어떻게 할지 고민해봅시다.

**Comment by JJuOn** [comment]
<user>
name
email
password
stuNo
phoneNo
lastVisited
verified

<board>
boardName

<post>
board
title
writer
views
content
date

<study>
owner
member
title
content
startDay
endDay
aboutLink

<comment>
writer
content

<file>
url

**Comment by JustKode** [comment]
@JJuOn Board Model을 위한 Comment 뿐만 아니라, Study Model을 위한 Comment도 만들어야 할 것 같습니다

**Comment by JustKode** [comment]
+ Post에 View 추가

**Comment by dhdbstjr98** [comment]
``user``
name
email
password
stuNo
phoneNo
lastVisited
isVerified

``board``
id (id를 굳이 둔 이유는 주소창에 게시판 id가 들어갈텐데 이 부분이 숫자로 되어있으면 유저가 접속시 직관적이지 않기 때문.)
name
skin

``post_boardId (게시판별로 테이블을 만든다. db 성능을 위함)``
title (null, 댓글의 경우 title을 사용하지 않음)
content
writer (작성시 작성자의 user.name의 값을 넣는다. 굳이 userNo와 함께 사용하는 이유는 db 조회시 성능을 높이기 위함과 비회원 작성 기능에 확장성을 두기 위함.)
parent (null, parent가 있으면 그 parent의 댓글임. null인 경우 원글임.)
userIdx (fk.user.idx, null)
hit
writedAt
link

``post_study``
post 테이블과 동일한데 아래 필드가 추가됨.
- startDate
- endDate

``post_study_member``
studyIdx (fk.post_study.idx)
userIdx (fk.user.idx)
name (참여자의 user.name을 넣는다. 굳이 따로 둔 이유는 게시판 테이블과 동일)

``board_file``
boardId (fk.board.id)
postIdx (fk.post_boardId.idx)
filename
url


쓰고보니까 unserscore랑 camelcase를 섞어서 썼는데 제가 db 설계할 때 주로 underscore로 사용하다보니까 습관들었나봅니다. 알아서 필터링해주세요 ㅜㅜ
